export const categoryList = [
    {
        id: 1,
        name: 'branding',
        description: 'Tenha a sua marca fixada na mente do consumidor',
        color: 'var(--branding-color)',
        imgPath: 'branding-icon.svg',
        link: '/branding',
    },
    {
        id: 2,
        name: 'design',
        description: 'Tenha a sua marca fixada na mente do consumidor',
        color: 'var(--design-color)',
        imgPath: 'design-icon.svg',
        link: '/design',
    },
    {
        id: 3,
        name: 'marketing digital',
        description:
            'marketing digital Conquiste presença online e transforme seu público em clientes',
        color: 'var(--marketing-color)',
        imgPath: 'marketing-digital-icon.svg',
        link: '/marketing-digital',
    },
    {
        id: 4,
        name: 'social media',
        description: 'Gere engajamento e conecte seu publico alvo',
        color: 'var(--social-media-color)',
        imgPath: 'social-media-icon.svg',
        link: '/social-media',
    },
    {
        id: 5,
        name: 'site e land pages',
        description: 'Conquiste o visitante com um site profissional',
        color: 'var(--sites-color)',
        imgPath: 'site-e-landing-page-icon.svg',
        link: '/sites',
    },
    {
        id: 6,
        name: 'e-commerce',
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. ',
        color: 'var(--e-commerce-color)',
        imgPath: 'e-commerce-icon.svg',
        link: '/e-commerce',
    },
    {
        id: 7,
        name: 'editoração e diagramação',
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. ',
        color: 'var(--editoracao-color)',
        imgPath: 'editoracao-e-diagramacao-icon.svg',
        link: '/editoracao-diagramacao',
    },
    {
        id: 8,
        name: 'foto e video',
        description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. ',
        color: 'var(--foto-color)',
        imgPath: 'foto-e-video-icon.svg',
        link: '/foto-video',
    },
]